
# https://hub.docker.com/repository/docker/rardcode/sambafs/tags

services:
  sambafs:
    image: rardcode/sambafs
    container_name: sambafs
    restart: unless-stopped
    privileged: true
    ports:
      - 137:137/udp
      - 138:138/udp
      - 139:139
      - 445:445
    environment:
    - TZ=Europe/Rome
    #  - USER1=1000|adam|pass
    #  - GROUP1=group|adam|eva
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./data:/data
    #- /srv/samba:/srv/samba
